apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cilist-fe.fullname" . }}-configmap
  labels:
    {{- include "cilist-fe.labels" . | nindent 4 }}
data:
  REACT_APP_BACKEND_URL: "http://{{ .Values.configuration.backend_url }}:{{ .Values.configuration.backend_port }}"