apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cilist-be.fullname" . }}-configmap
  labels:
    {{- include "cilist-be.labels" . | nindent 4 }}
data:
  # # cara kedua - dinamis
  {{ toYaml .Values.configuration | nindent 2 }}